### ISSUE TITLE
Preflight 404

### ISSUE THREAD

**Issue by garretteklof** [fastify/fastify-cors#105]
## 💥 Regression Report

Apologies, I'm unsure if this is a true regression because I haven't kept good track of version timeline, however the implementation I had was working (as recent as a day or two ago) and now it is not. The application now `404`s on preflight and disabling preflight via options seems to have no effect. There are a few old issues that seem pertinent to the problem I'm experiencing i.e. https://github.com/fastify/fastify-cors/issues/20. I'm new to Fastify, this could very well be my implementation, but I'm not trying to do anything fancy.

## Last working version

Worked up to version: 5.1.0

Stopped working in version: 5.1.0

## To Reproduce

```js
  void fastify.register(import("fastify-cors"), { preflight: false })
  void fastify.register(AutoLoad, {
    dir: join(__dirname, "plugins"),
    options: opts,
  })
  void fastify.register(AutoLoad, {
    dir: join(__dirname, "modules"),
    indexPattern: /.*routes(\.ts|\.js|\.cjs|\.mjs)$/,
    options: opts,
  })
```

## Expected behavior

To not fail on preflight.

<img width="531" alt="Screen Shot 2020-12-18 at 4 59 07 PM" src="https://user-images.githubusercontent.com/4140229/102668928-d749e500-4152-11eb-88fc-bb3c70d22a4f.png">

## Your Environment

- *node version*: 12
- *fastify version*: >=3.0.0
- *os*: Mac

**Comment by garretteklof** [comment]
This error is intermittent. It suddenly began working again after I explicitly set `origin: true` (but continued to work after I kept defaults). Any help addressing this will be much appreciated. Is there some specific way I should be ordering plugins to avoid a race condition? I'm not understanding why it's sporadic.

**Comment by mcollina** [comment]
Note that if you pass `preflight: false` it disable the preflight/`OPTIONS` route - thus you are hitting a 404.

**Comment by mcollina** [comment]
Please provide a full example to reproduce.

**Comment by garretteklof** [comment]
It's difficult to provide a full working example because unfortunately the error is not consistent, and providing the entire source code will probably be unhelpful (and it lives on a client's private repo). I'll keep this issue open for a bit and see if I can come up with something isolated / reproducible. Thank you for your quick response.

**Comment by garretteklof** [comment]
Have not been able to reproduce so it had to be somewhere within my implementation. If I happen to reencounter, I'll reopen. Thanks again.

**Comment by databrecht** [comment]
I have the same issue but it's a big monorepo so I can't easily give you a reproduction case. 
I had the same problem that it randomly worked, then stopped working. It worked initially as long as I was registering the route in the same file. From the moment I used that function registerSomeRoute it started to go wrong from time to time.
At the moment I added more routes, it went wrong almost consistently.

I wondered whether it could be that register is not truly done when it returns, could that be the cae since since I added the delay, things are magically solved.

```ts
  const fastifyServer = fastify({
  })
  await fastifyServer.register(cors, {
    origin: ['http://localhost:5173'], // allow Vite dev-fastifyServer
    methods: ['POST', 'GET', 'OPTIONS'],
  })
  await delay(10000) // <-- the fix

  registersomeRoute(fastifyServer)
```

**Comment by databrecht** [comment]
I don't need help, I can quite easily switch to express at this point. I was trying to be helpful since it seemed this solved the issue and could provide an indication as to why it happens. In every case, it wasn't helpful since it randomly broke again even with the delay. A few restarts later and random code changes such as adding a log and the preflight worked again. Probably something todo with how it runs/compiles. The same as what was said above applies, it's not consistent so reproducible code is going to be quite hard and I understand that it's therefore not an easy issue to solve (if it is an issue at all).
