### ISSUE TITLE
Request is processed even if origin not whitelisted

### ISSUE THREAD

**Issue by stephan9mertel** [fastify/fastify-cors#51]
Maybe I didn't get the concept of CORS right, but I'm facing the following issue:

I whitelist a domain http://example.com using
`server.register(fastifyCors, { origin: ["http://example.com"]});`

Then I define the following endpoint:
```
server.post("/mypost", async(request, response) => {
    foo();
    response.send("OK");
});
```

Now, if I receive a request from a domain other than http://example.com, I'd expect foo() not to be executed. However, it seems foo() is run always, no matter from which origin the request comes.

What am I missing here?

Thanks in advance!

**Comment by Eomm** [comment]
This plugin adds the standard CORS headers and this protocol should be implemented on both side: server and client.
By default, if you develop a react client that calls a remote server in another domain, the browser will block the request if the server doesn't reply this the CORS headers.
Check out https://enable-cors.org/ for more info

In order to block some request, I would use [fastify-auth](https://github.com/fastify/fastify-auth) plugin

**Comment by stephan9mertel** [comment]
Hi @Eomm, thanks for your answer. In our use case we just send POST requests from different origins to a server. The server should accept only requests from certain whitelisted domains.

If I get your answer and the enable-cors documentation right, this is not the purpose of CORS, is it? Thanks for the hint on fastify-auth, we'll have a look.
